### ISSUE TITLE
Firmware and wiring

### ISSUE THREAD

**Issue by Tim2309** [steve1066d/softub-wifi#1]
Hi, thank you for the great project. I'm planning to build your PCB but have some problems

**Wiring**
Do you have any pictures of the completed PCB and pictures mounted to the Softub controller?
Are the Parts soldered directly to the board or do you use headers so they can be removed?
Where do you mount the board in the pumpunit?

**Firmware**
this link doesn't work anymore
"https://wiki.seeedstudio.com/XIAO_ESP32S3_CircuitPython/"
is there any further discription how to write the firmware?

What about the Softub Replacement Firmware? Are you planning to do a seperate firmware for the softub itself and you don't need the PCB?

**Comment by hypertex1** [comment]
I second this. 
I'm also interested in this project but i'm not sure how much time i probably will need to spend for it. 
It would help a lot to see the completeted PCB mounted into the softub hydromate.

I also haven't worked with SEEED-controllers/studio and would be happy about something like a step by step checklist which firmware to use, how to get the programming done and so on.

I'm also not sure about this sentence in the description: "While there is support for handling controllers after 2011 that resond with "P" when up to temp, it hasn't been tested.". I have a softub fom 2020 with "P" in the display and 12/24h mode. I'm actually using 12h mode, and I'm not sure if it will work after patching it with this pcb.

My last point is the webservice funcitonality... Is it only possible to access some kind of website to interact with the pool, or is there some kind of API, so I can for example send an automated http.get to the pool to stop the jets?

@Tim2309 I hope ist ok that I "hijacked" your thread a little and extended it with further questions.

**Comment by Tim2309** [comment]
No Problem
I found a link on [Facebook](https://m.facebook.com/groups/2559170667722280/posts/3292406461065360/) 
[Link](https://steve1066d.github.io/devore.tubs/?fbclid=IwZXh0bgNhZW0CMTEAAR0Y49tb5C5OicrOuYct9r3rEEpu9JS6BZ15PHlNcteQWTaVInCe15jIovY_aem_WS8HzGRIYv195psQyvtu4A)

it looks like this project is dead and a new Controller is in development

**Comment by hypertex1** [comment]
That's interesting news. Thanks for the information!

**Comment by steve1066d** [comment]
This project isn't quite dead... I just didn't notice the issue :)
I do have a commercial product in the works (the replacement controller), but I'm still supporting this project as well.  This project has more bells and whistles.
Here's a picture of the board installed.   It isn't soldered to the board.
![wifi](https://github.com/user-attachments/assets/4c4ae70c-14c8-4cf5-8926-60c83380a60e)

**Comment by steve1066d** [comment]
The new URL for the firmware is here:  https://wiki.seeedstudio.com/xiao_esp32s3_project_circuitpython/

**Comment by steve1066d** [comment]
So many components to this issue... The final question, does it work with the newer boards... I think so, but if you run into issues, you can solder a jumper over JP4, which will make the new board act like the old board.

**Comment by steve1066d** [comment]
I think I've answered everything... if anything is outstanding, add a new issue
